paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: All products was gotten successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "401":
          description: Error por falta de permisos
        "500":
          description: Error interno del servidor
  /api/products/{pid}:
    get:
      summary: Get a product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the product id you want to get
          schema:
            $type: string
      responses:
        "200":
          description: The product was gotten successful
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "500":
          description: Internal Server Error
    put:
      summary: Update a product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the product id you want to update
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: The product was updated successful
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "500":
          description: Internal Server Error
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Product id generated by data base
        title:
          type: string
          description: product title
        description:
          type: string
          description: product description
        price:
          type: number
          description: product price
        thumbnail:
          type: string
          description: product thumbnail
        code:
          type: string
          description: product code
        stock:
          type: string
          description: product stock
        status:
          type: boolean
          description: product status
        category:
          type: string
          description: product category
        owner:
          type: string
          description: product owner
      example:
        _id: 64934f532fee8fd1ce51e596
        title: product1
        description: desc1
        price: 300
        thumbnail: "100"
        code: "100"
        stock: "100"
        status: true
        category: Ropa
        owner: 64933c9f6d7c7a3b5e484e71
  requestBodies:
    updateProduct:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Product id generated by data base
        title:
          type: string
          description: product title
        description:
          type: string
          description: product description
        price:
          type: number
          description: product price
        thumbnail:
          type: string
          description: product thumbnail
        code:
          type: string
          description: product code
        stock:
          type: string
          description: product stock
        status:
          type: boolean
          description: product status
        category:
          type: string
          description: product category
        owner:
          type: string
          description: product owner
      example:
        _id: 64934f532fee8fd1ce51e596
        title: product1
        description: desc1
        price: 300
        thumbnail: "100"
        code: "100"
        stock: "100"
        status: true
        category: Ropa
        owner: 64933c9f6d7c7a3b5e484e71
